/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Article {
    url: string;
    title: string;
    source: string;
    publishedAt: Time;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: Category;
    isPinned: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type ArticleId = bigint;
export interface UserProfile {
    name: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum Category {
    ipl = "ipl",
    tech = "tech",
    pakistan = "pakistan",
    cricket = "cricket",
    business = "business",
    sports = "sports",
    world = "world",
    politics = "politics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addManualArticle(newArticle: Article): Promise<ArticleId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearArticles(): Promise<void>;
    deleteArticle(id: ArticleId): Promise<void>;
    fetchBusinessNews(): Promise<string>;
    fetchIndiaNews(): Promise<string>;
    fetchCricketNews(): Promise<string>;
    fetchHeadlines(): Promise<string>;
    fetchSportsNews(): Promise<string>;
    fetchTechNews(): Promise<string>;
    fetchWorldNews(): Promise<string>;
    getArticles(category: Category | null, limit: bigint | null): Promise<Array<Article>>;
    getBreakingNews(): Promise<Array<Article>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeaturedArticle(): Promise<Article | null>;
    getPinnedArticles(): Promise<Array<Article>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setFeatured(id: ArticleId): Promise<void>;
    setPinned(id: ArticleId, pinned: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Article as _Article, Category as _Category, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addManualArticle(arg0: Article): Promise<ArticleId> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualArticle(to_candid_Article_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualArticle(to_candid_Article_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearArticles(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearArticles();
            return result;
        }
    }
    async deleteArticle(arg0: ArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async fetchBusinessNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBusinessNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBusinessNews();
            return result;
        }
    }
    async fetchCricketNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCricketNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCricketNews();
            return result;
        }
    }

    async fetchIndiaNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchIndiaNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchIndiaNews();
            return result;
        }
    }
    async fetchHeadlines(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchHeadlines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchHeadlines();
            return result;
        }
    }
    async fetchSportsNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSportsNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSportsNews();
            return result;
        }
    }
    async fetchTechNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTechNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTechNews();
            return result;
        }
    }
    async fetchWorldNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchWorldNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchWorldNews();
            return result;
        }
    }
    async getArticles(arg0: Category | null, arg1: bigint | null): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBreakingNews(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBreakingNews();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBreakingNews();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedArticle(): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedArticle();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedArticle();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedArticles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedArticles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setFeatured(arg0: ArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeatured(arg0);
            return result;
        }
    }
    async setPinned(arg0: ArticleId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPinned(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPinned(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Article_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : from_candid_Article_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    source: string;
    publishedAt: _Time;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: _Category;
    isPinned: boolean;
}): {
    url: string;
    title: string;
    source: string;
    publishedAt: Time;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: Category;
    isPinned: boolean;
} {
    return {
        url: value.url,
        title: value.title,
        source: value.source,
        publishedAt: value.publishedAt,
        summary: value.summary,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        isPinned: value.isPinned
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ipl: null;
} | {
    tech: null;
} | {
    pakistan: null;
} | {
    cricket: null;
} | {
    business: null;
} | {
    sports: null;
} | {
    world: null;
} | {
    politics: null;
}): Category {
    return "ipl" in value ? Category.ipl : "tech" in value ? Category.tech : "pakistan" in value ? Category.pakistan : "cricket" in value ? Category.cricket : "business" in value ? Category.business : "sports" in value ? Category.sports : "world" in value ? Category.world : "politics" in value ? Category.politics : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Article_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Article): _Article {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    source: string;
    publishedAt: Time;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: Category;
    isPinned: boolean;
}): {
    url: string;
    title: string;
    source: string;
    publishedAt: _Time;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: _Category;
    isPinned: boolean;
} {
    return {
        url: value.url,
        title: value.title,
        source: value.source,
        publishedAt: value.publishedAt,
        summary: value.summary,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        isPinned: value.isPinned
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    ipl: null;
} | {
    tech: null;
} | {
    pakistan: null;
} | {
    cricket: null;
} | {
    business: null;
} | {
    sports: null;
} | {
    world: null;
} | {
    politics: null;
} {
    return value == Category.ipl ? {
        ipl: null
    } : value == Category.tech ? {
        tech: null
    } : value == Category.pakistan ? {
        pakistan: null
    } : value == Category.cricket ? {
        cricket: null
    } : value == Category.business ? {
        business: null
    } : value == Category.sports ? {
        sports: null
    } : value == Category.world ? {
        world: null
    } : value == Category.politics ? {
        politics: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
