/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Category = IDL.Variant({
  'ipl' : IDL.Null,
  'tech' : IDL.Null,
  'pakistan' : IDL.Null,
  'cricket' : IDL.Null,
  'business' : IDL.Null,
  'sports' : IDL.Null,
  'world' : IDL.Null,
  'politics' : IDL.Null,
});
export const Article = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : Time,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'isPinned' : IDL.Bool,
});
export const ArticleId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addManualArticle' : IDL.Func([Article], [ArticleId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearArticles' : IDL.Func([], [], []),
  'deleteArticle' : IDL.Func([ArticleId], [], []),
  'fetchBusinessNews' : IDL.Func([], [IDL.Text], []),
  'fetchCricketNews' : IDL.Func([], [IDL.Text], []),
  'fetchHeadlines' : IDL.Func([], [IDL.Text], []),
  'fetchSportsNews' : IDL.Func([], [IDL.Text], []),
  'fetchTechNews' : IDL.Func([], [IDL.Text], []),
  'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
  'getArticles' : IDL.Func(
      [IDL.Opt(Category), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getBreakingNews' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
  'getPinnedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeatured' : IDL.Func([ArticleId], [], []),
  'setPinned' : IDL.Func([ArticleId, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'ipl' : IDL.Null,
    'tech' : IDL.Null,
    'pakistan' : IDL.Null,
    'cricket' : IDL.Null,
    'business' : IDL.Null,
    'sports' : IDL.Null,
    'world' : IDL.Null,
    'politics' : IDL.Null,
  });
  const Article = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : Time,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'isPinned' : IDL.Bool,
  });
  const ArticleId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addManualArticle' : IDL.Func([Article], [ArticleId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearArticles' : IDL.Func([], [], []),
    'deleteArticle' : IDL.Func([ArticleId], [], []),
    'fetchBusinessNews' : IDL.Func([], [IDL.Text], []),
  'fetchCricketNews' : IDL.Func([], [IDL.Text], []),
    'fetchHeadlines' : IDL.Func([], [IDL.Text], []),
    'fetchSportsNews' : IDL.Func([], [IDL.Text], []),
    'fetchTechNews' : IDL.Func([], [IDL.Text], []),
    'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
    'getArticles' : IDL.Func(
        [IDL.Opt(Category), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getBreakingNews' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
    'getPinnedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeatured' : IDL.Func([ArticleId], [], []),
    'setPinned' : IDL.Func([ArticleId, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };